import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--geist-bg))',
        surface: 'rgb(var(--geist-surface))',
        text: 'rgb(var(--geist-text))',
        'text-secondary': 'rgb(var(--geist-text-secondary))',
        'text-muted': 'rgb(var(--geist-text-muted))',
        border: 'rgb(var(--geist-border))',
        'border-hover': 'rgb(var(--geist-border-hover))',
        primary: 'rgb(var(--geist-primary))',
        'primary-hover': 'rgb(var(--geist-primary-hover))',
        'primary-foreground': 'rgb(var(--geist-primary-foreground))',
        success: 'rgb(var(--geist-success))',
        warning: 'rgb(var(--geist-warning))',
        error: 'rgb(var(--geist-error))',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        elevation0: 'var(--elevation-0)',
        elevation1: 'var(--elevation-1)',
        'elevation-1': 'var(--elevation-1)',
        elevation1b: 'var(--elevation-1b)',
        'elevation-1b': 'var(--elevation-1b)',
        elevation2: 'var(--elevation-2)',
        'elevation-2': 'var(--elevation-2)',
        elevation3: 'var(--elevation-3)',
        'elevation-3': 'var(--elevation-3)',
      },
      transitionDuration: {
        micro: 'var(--duration-micro)',
        fast: 'var(--duration-fast)',
        DEFAULT: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
      },
      fontSize: {
        'heading-72': ['var(--text-heading-72)', { lineHeight: 'var(--leading-tight)' }],
        'heading-64': ['var(--text-heading-64)', { lineHeight: 'var(--leading-tight)' }],
        'heading-56': ['var(--text-heading-56)', { lineHeight: 'var(--leading-tight)' }],
        'heading-40': ['var(--text-heading-40)', { lineHeight: 'var(--leading-tight)' }],
        'heading-32': ['var(--text-heading-32)', { lineHeight: 'var(--leading-snug)' }],
        'heading-24': ['var(--text-heading-24)', { lineHeight: 'var(--leading-snug)' }],
        'copy-24': ['var(--text-copy-24)', { lineHeight: 'var(--leading-normal)' }],
        'copy-20': ['var(--text-copy-20)', { lineHeight: 'var(--leading-normal)' }],
        'copy-18': ['var(--text-copy-18)', { lineHeight: 'var(--leading-normal)' }],
        'copy-16': ['var(--text-copy-16)', { lineHeight: 'var(--leading-normal)' }],
        'copy-14': ['var(--text-copy-14)', { lineHeight: 'var(--leading-normal)' }],
        'label-20': ['var(--text-label-20)', { lineHeight: 'var(--leading-normal)' }],
        'label-16': ['var(--text-label-16)', { lineHeight: 'var(--leading-normal)' }],
        'label-14': ['var(--text-label-14)', { lineHeight: 'var(--leading-normal)' }],
        'label-12': ['var(--text-label-12)', { lineHeight: 'var(--leading-normal)' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
}

export default config